export enum PermissionNames {
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER = 'UPDATE_USER',
  VIEW_USER = 'VIEW_USER',

  CREATE_PRODUCT = 'CREATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  VIEW_PRODUCT = 'VIEW_PRODUCT',

  CREATE_ORDER = 'CREATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  VIEW_ORDER = 'VIEW_ORDER',

  CREATE_REVIEW = 'CREATE_REVIEW',
  DELETE_REVIEW = 'DELETE_REVIEW',
  UPDATE_REVIEW = 'UPDATE_REVIEW',
  VIEW_REVIEW = 'VIEW_REVIEW',
}
